### PR TITLE
a simple npe example

### PR DESCRIPTION
**Pull request by Axolot1**
While  Inspecting the project,  click "npe example" button and then rotate the screen. #381

### CODE REVIEW

**Comment by longinoa** [comment]
Thanks @Axolot1!

**Comment by rickbrew** [comment]
Great :) Looking at things now ...

**Comment by rickbrew** [comment]
I've got a repro 👍  Debugging now ...

**Comment by rickbrew** [comment]
This PR was really helpful, and in fact instrumental, in helping me fix #381. Thanks so much :)

I would like to find some time to merge this in at some point. Probably with a few modifications. I think it's the start of a fantastic Elements testing harness/playground.

**Comment by Axolot1** [comment]
It is my first PR on github， glad it help:smile:.

**Comment by jasta** [comment]
Can this PR be closed as it was used just to help fix a bug?

**Pull request closed without merging**
