### PR TITLE
Remove redundant modifiers from interfaces

### PR DESCRIPTION
**Pull request by VEINHORN**

### CODE REVIEW

**Comment by jasta** [comment]
Hmm, I actually prefer the redundant keywords :\  Helps me to not assume that things are package private, non-static, etc residing inside a regular class.

**Comment by felipecsl** [comment]
i think it makes sense to remove them since it's just redundant information/noise

**Comment by jasta** [comment]
@felipecsl alright, you convinced me :)

**Comment by felipecsl** [comment]
Whoohoo thanks!!!

**Pull request merged**
