### PR TITLE
Update Gradle wrapper and plug-in

### PR DESCRIPTION
**Pull request by friederbluemle**
This updates Gradle wrapper to `2.14` and the plug-in to `2.1.2` (latest versions as of Jun 22, 2016)

### CODE REVIEW

**Comment by friederbluemle** [comment]
Pull request updated with Gradle wrapper `2.14`.

**Comment by friederbluemle** [comment]
Updated again to `2.14.1` and rebased. @jasta Can you merge please?

**Comment by longinoa** [comment]
hey @friederbluemle  sorry for the delay, @jasta  is on vacation Im looking at this now

**Comment by longinoa** [comment]
Thanks!

**Comment by friederbluemle** [comment]
@longinoa No worries. Meanwhile, there were even more updates: #417 :)

**Pull request merged**
