### PR TITLE
updated Timber dependency version to 4.1.2

### PR DESCRIPTION
**Pull request by mmirhoseini**
this old Timber version causes me many troubles,
so please merge this new version fix

### CODE REVIEW

**Comment by jasta** [comment]
Can you squash your diffs into one now that it's only a simple 2 line patch?

**Comment by mmirhoseini** [comment]
I don't know what do you mean! and what should I do...

**Comment by jasta** [comment]
Your current PR is comprised of 5 individual git commits, even though most of them are now "empty" because I already made the changes contained within them.  Git offers a feature to let you merge those into 1 so that it looks cleaner in our version control tree:

http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by mmirhoseini** [comment]
Hi,
I create a new pull request:
**update timber version #396**

**Comment by mmirhoseini** [comment]
Hi,

I create a new pull request:
update timber version #396 <https://github.com/facebook/stetho/pull/396>

I hope everything goes fine.

Best regards,

Mohsen Mirhoseini Argi

**Pull request closed without merging**
