### PR TITLE
Fix ObjectMapper's treatment of static fields

### PR DESCRIPTION
**Pull request by rickbrew**
We should not be setting static fields from JSON data, or serializing them into JSON data. This prevents Stetho from working with Android Studio's Instant Run since it injects some stuff into there. This can manifest itself as a blank Elements tab, as well as no incoming data on any of the other tabs.

### CODE REVIEW

**Comment by longinoa** [comment]
:+1: Thanks @rickbrew

**Comment by xiabi** [comment]
Hi. How can I update the jar, your commit didn't  come with a new version no.

**Comment by longinoa** [comment]
@xiabi we are still working on a couple of more fixes before releasing a new version. You can pull master down and build locally in the mean time.

**Comment by xiabi** [comment]
thanks for your work.

but it seem that this problem still exists.

image

**Pull request merged**
