### PR TITLE
Fix #607: Stetho view inspection crashing apps on Android P DP4

### LINKED ISSUE #607: Stetho view inspection crashing apps on Android P DP4
Looks like the Stetho element inspection is crashing on the latest Android P developer preview. Using an emulator with build number `sdk_gphone_x86-userdebug 9 PPP4.180612.0074860066 dev-keys`, I get this crash when trying to do an inspection of my view elements:

``07-16 09:04:25.244 9124-9124/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.iotas.installer, PID: 9124
    java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed
        at android.graphics.Canvas.checkValidClipOp(Canvas.java:779)
        at android.graphics.Canvas.clipRect(Canvas.java:826)
        at com.facebook.stetho.inspector.elements.android.ViewHighlightOverlays$ViewHighlightOverlaysJellybeanMR2$MainHighlightDrawable.draw(ViewHighlightOverlays.java:141)
        at android.view.ViewOverlay$OverlayViewGroup.dispatchDraw(ViewOverlay.java:256)
        at android.view.View.draw(View.java:20216)
        at com.android.internal.policy.DecorView.draw(DecorView.java:780)
        at android.view.View.updateDisplayListIfDirty(View.java:19082)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3312)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3116)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2485)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7184)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)``

Let me know if there's any other way I can help! Tried this on an older build of Android with no issues.

### PR DESCRIPTION
**Pull request by rogerhu**
Fix for https://github.com/facebook/stetho/issues/607

https://github.com/facebook/stetho/commit/8874c9ff0b593d5530ffac5fd499a8147356e7cf

@jasta @aadsm

### CODE REVIEW

**Comment by something15525** [comment]
Nice work, thanks for submitting this!

**Comment by jasta** [comment]
Thanks!

**Comment by jasta** [comment]
I'd like to start prepping another release with this change and several others in soon!

**Comment by something15525** [comment]
@jasta 👍

**Pull request merged**
