### PR TITLE
Update build dependencies

### PR DESCRIPTION
**Pull request by friederbluemle**
Updates:
- Android Gradle plugin `2.3.3`
- Gradle wrapper `4.1`

### CODE REVIEW

**Comment by friederbluemle** [comment]
Rebased onto latest `master` branch.

**Comment by friederbluemle** [comment]
Updated to `2.3.2`.

**Comment by friederbluemle** [comment]
Updated to `2.3.3`.

**Comment by friederbluemle** [comment]
Updated to latest versions and rebased.

**Comment by jasta** [comment]
Sure why not, thanks :)

**Pull request merged**
