### PR TITLE
Add a screenshot of the javascript console with a description

### PR DESCRIPTION
**Pull request by potyl**
This branch updates the stetho github gh-pages website to include a screenshot of the javascript console.

### CODE REVIEW

**Comment by jasta** [comment]
Awesome :)

**Comment by jasta** [comment]
I'm going to merge this when we cut the next release.

**Comment by potyl** [comment]
Makes sense, i doubt that this branch will require more work and cause much conflicts. It can wait to be merged as long as it takes.

Do you have an idea when the next release will be available?

**Comment by jasta** [comment]
Looking at cutting a big feature release in a couple weeks.  If we don't
have other features ready by then I'll push to just ship with your console
support and bug fixes.

**Pull request merged**
